### ISSUE TITLE
script adds api to the username in the url

### ISSUE THREAD

**Issue by bhoffman314** [redhatjobin/bitbucket-backup#2]
When I run the script all of the entries in bitbucketurls looks like:

git@bitbucket.org:/apiUSER_NAME/REPO_NAME.git

Where it is totally correct if the three letters api are removed but this means nothing works and I don't know enough bash to try to debug it.

**Comment by DJLink** [comment]
I have the same issue/error, been trying to change it to work but unsuccessfully

**Comment by abhishekvp** [comment]
I was able to fix this! Please change line 26 in bitbucket-backup.sh(https://github.com/redhatjobin/bitbucket-backup/blob/master/bitbucket-backup.sh#L26) to 
"sed 's/\/api\/1\.0\/repositories\///g' bitbucket.4 > bitbucket.5"

**Comment by abhishekvp** [comment]
I have fixed the "api" prefix issue. I have made a pull request to this repository. You can find the fixed version of this script at https://github.com/abhishekvp/bitbucket-backup/blob/master/bitbucket-backup.sh

**Comment by DJLink** [comment]
@abhishekvp thanks, that surely makes it work now, script works. 
But I'm still getting a permission denied error when cloning the repos, although I created the app password with read rights on everything, any idea why?

![image](https://user-images.githubusercontent.com/423769/57438373-a944b500-723b-11e9-83a2-11f4b7c0029d.png)

**Comment by abhishekvp** [comment]
@DJLink I think this error is because you haven't added your machine's Public Key to your Bitbucket Account. Please refer this: https://confluence.atlassian.com/bitbucket/access-keys-294486051.html

**Comment by DJLink** [comment]
ah yeah that makes sense, thanks for the info
